Shane image
Expensify/clipboard pull request #1
Opened 2021-09-01 18:51 UTC by MTN718

Added setImage method for Web,Android,IOS Platform
Parameter is Image URL

2021-09-03 00:10 UTC, roryabraham requested changes

2021-09-03 00:10 UTC, roryabraham commented on android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
> +    // Bitmap Image
Not sure this comment is useful

2021-09-03 00:10 UTC, roryabraham commented on android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
> +    File file= Environment.getExternalStorageDirectory();
```suggestion
    File file = Environment.getExternalStorageDirectory();
```

2021-09-03 00:10 UTC, roryabraham commented on android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
> +      ContentResolver theContent = getContext().getContentResolver();
```suggestion
      ContentResolver contentResolver = getContext().getContentResolver();
```

2021-09-03 00:10 UTC, roryabraham commented on android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
> +      ClipData clipdata = ClipData.newUri(theContent, dest.getName(), imageUri);
```suggestion
      ClipData clipData = ClipData.newUri(theContent, dest.getName(), imageUri);
```

2021-09-03 00:10 UTC, roryabraham commented on src/Clipboard.ts
> +  setImage(imageUrl: string) {
Missing JSDoc

2021-09-03 00:10 UTC, roryabraham commented on src/Clipboard.web.ts
> +  setImage(imageUrl:string){
Missing JSDoc

2021-09-03 00:10 UTC, roryabraham commented on src/Clipboard.ts
> +      .then((response) => {
```suggestion
      .then((response: Response) => {
```

2021-09-03 00:10 UTC, roryabraham commented on src/Clipboard.ts
> +      .then( blob => new Promise( callback =>{
```suggestion
      .then(blob: Blob => new Promise(() => {
```

`callback` seems unused.

2021-09-03 00:10 UTC, roryabraham commented on src/Clipboard.ts
> +          let reader = new FileReader() ;
```suggestion
          let reader = new FileReader();
```

2021-09-03 00:10 UTC, roryabraham commented on src/Clipboard.ts
> +          reader.onload = function(){
This is a bit confusing – you're using a regular function an not an arrow function because you want `this` to refer to the `FileReader`?

I might change this like so:

```javascript
reader.onload = () => {
    let base64Data = reader.result.replace("image/jpeg", "image/png");
    NativeClipboard.setImage(base64Data);
}
```

2021-09-03 00:10 UTC, roryabraham commented on src/Clipboard.ts
> +    fetch(imageUrl)
Probably want to return the promise from this function:

```suggestion
    return fetch(imageUrl)
```

2021-09-03 00:10 UTC, roryabraham commented on src/Clipboard.ts
> +      .catch(() => {
Probably want to remove this `catch` block as it's not doing anything right now.

2021-09-03 00:10 UTC, roryabraham commented on src/Clipboard.web.ts
> +    write(data:Array<any>):Promise<void>;
```suggestion
    write(data:Array<any>): Promise<void>;
```

2021-09-03 00:10 UTC, roryabraham commented on src/Clipboard.web.ts
> +  setImage(imageUrl:string){
with some more types and using purely async/await:

```javascript
async function setImage(imageURL: string): Promise<void> {
	if (navigator && navigator.clipboard) {
	      const response: Response = await fetch(imageURL);
	      if (!response.ok) { throw Error(response.statusText); }
	      const blob: Blob = await response.blob();
	      const reader = new FileReader();
	      reader.onload = async () => {
	          let base64Data = this.result as string;
	          base64Data = base64Data.replace("image/jpeg", "image/png");
	          const base64Response: Response = await fetch(base64Data);
	          const innerBlob: Blob = await base64Response.blob();
	          await navigator.clipboard.write([new ClipboardItem({"image/png": innerBlob})]);
	      }
	      await reader.readAsDataURL(blob);
	}
}
```

2021-09-03 00:10 UTC, roryabraham commented on tsconfig.json
> +    "skipLibCheck": true
I'm somewhat doubtful that the upstream maintainers will be okay with enabling `skipLibCheck`

2021-09-03 00:12 UTC, roryabraham commented
I need a second reviewer from one of our more engineers more experienced in native mobile development. Unfortunately I'm very unfamiliar with Objective-C

2021-09-03 00:13 UTC, roryabraham commented
@Expensify/mobile-deployers Any volunteers please? I need a second opinion on this PR. It's related to https://github.com/Expensify/App/issues/4629

2021-09-03 06:08 UTC, MTN718 commented
Ok let me fix following your feedback.

2021-09-03 06:09 UTC, MTN718 commented on android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
> +    // Bitmap Image
To decode base64 in android, need to remove prefix.

2021-09-03 06:29 UTC, MTN718 commented on src/Clipboard.ts
> +    fetch(imageUrl)
not sure this one, can you explain better?

2021-09-03 11:30 UTC, Julesssss requested changes
Sorry for the late review here. I think we should continue with the Web/Desktop/mWeb copy image logic, but remove the Android/iOS clipboard copy functionality. We shouldn't port this desktop feature to mobile. 

Sharing images on both mobile platforms should be done via their native share functionality ([Android](https://developer.android.com/training/sharing), [iOS](https://developer.apple.com/design/human-interface-guidelines/ios/extensions/sharing-and-actions/)). This allows the user to share images to any app which has registered their support of receiving images. 

The one case that this might be considered useful is for sharing internally within our app, but again we should not depend on copy/paste here. We should instead register our app as a receiver of images (native share), which allows any other app to share images directly into our chats. If we are desperate to add this functionality right now then instead we can build our own UI for sharing images to a different chat.

2021-09-03 14:51 UTC, Jag96 reviewed
@MTN718 can you please update the issue description to include the issue link and your testing steps?

2021-09-03 14:56 UTC, Julesssss commented
Update to my review: @roryabraham let me know that this is actually common on iOS, so I take back that part of my argument. But I still strongly feel that it's not worth hacking an Android solution purely for feature parity here.

2021-09-03 14:59 UTC, Julesssss commented on android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
> +    // Bitmap Image
I think the point is that the variable is already named `Bitmap`, so the comment adds nothing here.

2021-09-03 15:06 UTC, Julesssss commented on android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
> +    }
We probably shouldn't silently fail here. Can we callback to the JS layer that the copy failed?

2021-09-03 15:07 UTC, Julesssss commented on ios/NSData+Base64.m
> +static unsigned char base64DecodeLookup[256] =
😬

2021-09-03 15:08 UTC, Julesssss commented on src/Clipboard.ts
> +  setImage(imageUrl: string) {
Unrelated, but what is a `.ts` file? Is that for typescript or something?

2021-09-03 15:09 UTC, Julesssss commented on src/Clipboard.web.ts
> +              // Growl.error(errorDesc);
Useless lines. Can we handle the error properly?

2021-09-03 16:48 UTC, roryabraham commented on src/Clipboard.ts
> +  setImage(imageUrl: string) {
Yep, TypeScript.

2021-09-03 16:50 UTC, AndrewGable commented on android/src/main/java/com/reactnativecommunity/clipboard/ClipboardModule.java
> +      values.put(MediaStore.Images.Media.MIME_TYPE,"image/png");
```suggestion
      values.put(MediaStore.Images.Media.MIME_TYPE, "image/png");
```

Can you just run google format on this whole file? https://google.github.io/styleguide/javaguide.html

There should be a plugin for whatever editor you are using.

2021-09-03 16:50 UTC, roryabraham commented on src/Clipboard.ts
> +    fetch(imageUrl)
Oh, basically this is a function that performs some asynchronous actions that take some time to complete. Right now, the function isn't returning anything. But if you return a promise (even if it's a void promise), then when using this function we can wait for the image to finish copying to the clipboard _then_ do something else.

```javascript
Clipboard.setImage(myURL).then(() => doSomethingElse());
```

2021-09-03 16:52 UTC, AndrewGable commented
The objective-c looks fine to me, but fair warning it's been a while since I've written any myself.

2021-09-03 19:25 UTC, roryabraham commented
A question that just came to mind – we're using `fetch` to fetch the URL of an image in this code ... does that mean we're reliant on having a network connection for copying the image to the clipboard to work? Like, if we've got our app open but we're on a plane and have no internet connection, will we still be able to copy an image to the clipboard?

2021-09-04 12:48 UTC, MTN718 commented
Question: Need to remove copy image code for android?

2021-09-06 07:01 UTC, MTN718 commented
Fixed following feedback @roryabraham

2021-09-08 17:57 UTC, MTN718 commented
Can you check and give me feedback? @roryabraham

2021-09-09 00:45 UTC, roryabraham commented
Did you have any comment on [this question](https://github.com/Expensify/clipboard/pull/1#issuecomment-912761173)?

2021-09-09 06:32 UTC, MTN718 commented
Regarding this question, can't copy clipboard on internet because currently system provide url of attachment so it should be fetch content of image from internet.

2021-09-09 09:20 UTC, Julesssss commented
> can't copy clipboard on internet because currently system provide url of attachment so it should be fetch content of image from internet.

Hmm, that seems a bit of a problem. It makes the feature inconsistent 😕

2021-09-09 09:22 UTC, MTN718 commented
> > can't copy clipboard on internet because currently system provide url of attachment so it should be fetch content of image from internet.
> 
> Hmm, that seems a bit of a problem. It makes the feature inconsistent 😕

But to get base64 image data from image url, fetch image necessary

2021-09-09 10:41 UTC, Julesssss commented
> But to get base64 image data from image url, fetch image necessary. Or we can send parameter base64 image for that library and fetch action in the app code.

Can you expand on the second part of your sentence, please? I think you are suggesting that this would work offline? Presumably the iOS apps that implement image copy/paste have solved this without requiring a connection?

2021-09-09 13:03 UTC, MTN718 commented
Regarding those ios app, it is getting UIImage from UIImageView and set  UIImage to Clipboard. But in expensify app, currently not getting UIImage from chat image, only url, so fetch base64 data from url and make UIImage and set to clipboard

2021-09-13 15:10 UTC, MTN718 commented
@roryabraham Please give me feedback

2021-09-13 22:58 UTC, roryabraham commented
Basically, we need this feature to work offline. The current approach won't work offline, and it sounds like this one won't either:

> I mean we can fetch image base64 data in the app and send base64 image data to library for clipboard and handle base64 data in the library not image url

So it sounds like what we need is something more like this:

1. This library's `setImage` function needs to take a RN image component
1. Then use the RN bridge + native code to get the base64 image data directly from the UIImage
1. Then process the base64 image and set it to the clipboard.

2021-09-14 15:21 UTC, MTN718 commented
@roryabraham Then in app, need to fetch base64 image data from url and pass that data object when we call library to copy clipboard, and handle that image data in native. Because currently message is img element with url

![image](https://user-images.githubusercontent.com/12084368/133285874-d096f6af-9b52-4e18-904a-0a029c824a71.png)

2021-09-14 16:36 UTC, roryabraham commented
@MTN718 That solution still won't work offline – it just moved the `fetch` from inside the Clipboard library to our app.

2021-09-14 16:40 UTC, MTN718 commented
But current app's structure store message to img element so can get only image url

2021-09-16 04:49 UTC, kadiealexander commented
Hi @MTN718, I've placed this issue on hold as per [this update](https://expensify.slack.com/archives/C01GTK53T8Q/p1631754482374800), as we are prioritising issues related to a feature release scheduled for 9/24. As an apology for the delay, we will add a $100 bonus as a thank you for waiting.

2021-10-22 15:05 UTC, MTN718 commented
this PR still hold?

2021-10-25 18:11 UTC, roryabraham commented
PR is no longer on HOLD, however, we'll need a solution that works offline.

2022-02-08 23:36 UTC, closed without merging